# This file was generated by RobotAgent.cs
from enum import IntEnum


class RobotObservations(IntEnum):
    # Accessible by self.obs.'field_name'
    robot_position_x = 0
    robot_position_y = 1
    robot_position_z = 2
    robot_velocity_x = 3
    robot_velocity_z = 4
    debris_position_x = 5
    debris_position_y = 6
    debris_position_z = 7
    dropzone_position_x = 8
    dropzone_position_y = 9
    dropzone_position_z = 10
    times_won = 11
    time_elapsed = 12
